services:
  dev:
    build: .
    volumes:
      - ../workspace:/app/workspace
      - ./.bashrc:/root/.bashrc
      - ./.vimrc:/root/.vimrc
    environment:
      - GEMINI_API_KEY=${GEMINI_API_KEY}
    stdin_open: true
    tty: true
