services:
  dev:
    build: .
    volumes:
      - ..:/app/workspace
      - ./.bashrc:/root/.bashrc
      - ./.vimrc:/root/.vimrc
      - ./.gitconfig:/root/.gitconfig
    environment:
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - GIT_USER=${GIT_USER}
      - GIT_PWD=${GIT_PWD}
    ports:
      - "8888:8888"
    stdin_open: true
    tty: true
